### PR TITLE
change company profile

### PR DESCRIPTION
**Pull request by thaidoandat**
## Related Tickets
- [#40253](https://edu-redmine.sun-asterisk.vn/issues/40253)

## WHAT (optional)
- Đổi trang công ty giống trang quản lý
- Thêm thanh search

## Evidence (Screenshot or Video)
Screenshot from 2021-08-17 08-17-07

### CODE REVIEW

**Comment by hau1862** [comment]
ok

**Comment by letterforyou26** [comment]
ok

**Comment by thaidoandat** [comment]
ok

**Comment by thaidoandat** [comment]
ready

**Comment by thaidoandat** [comment]
ready

**Comment by thaidoandat** [comment]
ready

**Pull request merged**
